# 调试

## 抛出异常

- 在Python中，如果尝试执行无效代码，就会抛出异常。异常是一个事件，它会在程序执行过程中发生，影响了程序的正常流程。
- 在Python中，异常是一个对象，表示一个错误或者异常条件。当Python脚本发生异常时，它会创建一个异常对象。如果你编写的代码处理了这个异常，程序会继续运行。否则，程序会停止，并显示一个traceback，它包含了异常信息以及程序中的哪些代码行导致了这个错误。

```python
raise Exception('This is the error message.')
```

## 取得回溯字符串

- 如果Python遇到错误，就会生成一些错误信息，称为“回溯”。回溯信息包含了错误信息，导致该错误的代码行号，以及导致该错误的函数调用的序列。这个序列被称为“调用栈”。

```python
import traceback
try:
    raise Exception('This is the error message.')
except:
    errorFile = open('errorInfo.txt', 'w')
    errorFile.write(traceback.format_exc())
    errorFile.close()
    print('The traceback info was written to errorInfo.txt.')
```

## 断言

- “断言”是一种内部的自我检查，用于确保代码没有做明显错误的事情。这些健全性检查由assert语句执行。如果检查失败，就会抛出异常。

```python
ages = [26, 57, 92, 54, 22, 15, 17, 80, 47, 73]
ages.sort()
assert ages[0] <= ages[-1]  # Assert that the first age is <= the last age.
```

## 日志

- 日志是一种记录程序执行过程中发生的事件的方式。使用Python的`logging`模块，可以在程序运行时输出这些日志消息。

```python
import logging
logging.basicConfig(level=logging.DEBUG, format=' %(asctime)s - %(levelname)s - %(message)s')
logging.debug('Start of program')
```

## 整理成笔记

| 函数/方法                            | 说明                                         | 可选参数                                 |
| ------------------------------------ | -------------------------------------------- | ---------------------------------------- |
| `raise Exception(message)`           | 抛出异常，中断程序运行                       | `message`: 异常信息                      |
| `traceback.format_exc()`             | 返回一个字符串，包含异常信息和堆栈跟踪的内容 | 无                                       |
| `assert condition, message`          | 如果条件不满足，则抛出异常                   | `condition`: 条件<br>`message`: 异常信息 |
| `logging.basicConfig(level, format)` | 设置日志的输出格式和级别                     | `level`: 日志级别<br>`format`: 日志格式  |
| `logging.debug(message)`             | 输出一条debug级别的日志信息                  | `message`: 日志信息                      |
| `logging.info(message)`              | 输出一条info级别的日志信息                   | `message`: 日志信息                      |
| `logging.warning(message)`           | 输出一条warning级别的日志信息                | `message`: 日志信息                      |
| `logging.error(message)`             | 输出一条error级别的日志信息                  | `message`: 日志信息                      |
| `logging.critical(message)`          | 输出一条critical级别的日志信息               | `message`: 日志信息                      |
| `logging.disable(level)`             | 禁用所有指定级别及以下级别的日志信息         | `level`: 日志级别                        |

## 习题解答

1. 如果变量spam是一个小于10的整数，断言语句为：

```python
assert spam >= 10, 'The spam variable is less than 10.'
```

2. 如果eggs和bacon包含的字符串相同（不区分大小写），断言语句为：

```python
assert eggs.lower() != bacon.lower(), 'The eggs and bacon variables are the same!' or assert eggs.upper() != bacon.upper(), 'The eggs and bacon variables are the same!'
```

3. 要编写一条断言语句，使其总是触发AssertionError，可以使用以下代码：

```python
assert False, 'This assertion always triggers.'
```

4. 为了能调用logging.debug()，程序中必须加入以下两行代码：

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

5. 为了让logging.debug()将日志消息发送到名为programLog.txt的文件中，程序必须加入以下两行代码：

```python
import logging
logging.basicConfig(filename='programLog.txt', level=logging.DEBUG)
```

6. 5个日志级别是：DEBUG, INFO, WARNING, ERROR, CRITICAL。

7. 你可以加入以下一行代码来禁用所有的日志消息：

```python
logging.disable(logging.CRITICAL)
```

8. 显示同样的消息，为什么使用日志消息比使用print()要好？

使用日志消息比使用print()要好，因为日志消息可以提供很多有用的功能，如设置日志级别以过滤出你想看到的消息级别，以及自动记录发生事件的时间和在哪里发生。

9. 调试控制窗口中的Step Over、Step In和Step Out按钮有什么区别？

- Step Over：执行下一行代码，但是如果该行代码是一个函数调用，那么将“跳过”该函数，以正常速度执行该函数的代码，然后在函数返回后暂停。
- Step In：执行下一行代码，如果该行代码是一个函数调用，那么将“进入”该函数，并跳转到该函数的第一行代码。
- Step Out：执行代码，直到从当前函数返回。

10. 单击Continue按钮后，调试器何时会停下来？

单击Continue按钮后，调试器会在遇到下一个断点时停下来。如果没有设置断点，那么程序将会继续执行，直到结束。

11. 什么是断点？

断点是一个标记，设置在你希望暂停程序执行的代码行上。当程序运行到设置了断点的代码行时，如果调试器是激活的，那么它将暂停程序的执行。

12. 在Mu中，如何在一行代码上设置断点？

在Mu中，你可以通过单击代码行左侧的空白区域或者行号来在一行代码上设置断点。设置断点后，该行代码左侧会出现一个红点来表示断点。

## 实践项目

### 调试硬币抛掷程序

```python
import random 
guess = ''
while guess not in ('heads', 'tails'):
    print('Guess the coin toss! Enter heads or tails:') 
    guess = input()
toss = random.randint(0, 1)  # 0 is tails, 1 is heads
if toss == 0:
    toss = 'tails'
else:
    toss = 'heads'
if toss == guess:
    print('You got it!') 
else:
    print('Nope! Guess again!') 
    guess = input()
    if toss == guess:
        print('You got it!')
    else:
        print('Nope. You are really bad at this game.')
```

在这个修复的版本中，我首先将toss的值从整数（0或1）修改为字符串（'heads'或'tails'），这样就可以直接将其与guess进行比较。然后，我添加了一个额外的input()调用，以便在第一次猜测失败后让用户有机会再次猜测。
